### PR TITLE
Replace header tag by head in html files of js examples

### PR DESCRIPTION
**Pull request by vishniakov-nikolai**

### CODE REVIEW

**Comment by vishniakov-nikolai** [comment]
@microsoft-github-policy-service agree

**Comment by vishniakov-nikolai** [comment]
> @vishniakov-nikolai please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="Intel"]

**Comment by vishniakov-nikolai** [comment]
> @vishniakov-nikolai the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
> ```

@microsoft-github-policy-service agree company="Intel"

**Comment by vishniakov-nikolai** [comment]
> @vishniakov-nikolai please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Intel"

**Comment by vishniakov-nikolai** [comment]
Hi guys! Could we merge or close this PR?
@jywu-msft @snnn @fs-eire

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
