### PR TITLE
Remove deprecated API usage

### PR DESCRIPTION
**Pull request by yuslepukhin**
`GetInputName/GetOutputName` has been deprected last release and now removed.

### CODE REVIEW

**Review by snnn — APPROVED** [review]

**Comment by snnn** [comment]
I had a discussion with @yuslepukhin offline, we decided to merge this PR first despite it will cause pipeline failures. Because we want to unblock ORT release first. Otherwise we will stick in a deadlock.

**Comment by jywu-msft** [comment]
when will we fix the pipeline failures? 
it caused me some confusion because I didn't know why it was failing at first. 
@hectorsvc FYI

**Comment by yuslepukhin** [comment]
> when will we fix the pipeline failures? it caused me some confusion because I didn't know why it was failing at first. @HectorSVC FYI

I am open to suggestions. Apparently, with the current setup it will fix itself with the new release. From my conversation with with @snnn the samples are based on the previous release and that needs to be fixed.

**Comment by snnn** [comment]
Ideally we should make our code be compatible with the latest ORT release and the latest ORT code in the main branch.  If we can't make it happen, I will modify the pipeline so that it would use a fixed version ORT nightly package instead.  Does it sound good?

**Pull request merged**
